name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: add build target
        run: rustup target add wasm32-wasip1
      - name: Build
        run: cargo build --verbose --release
